- release-notes-1.0.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=795027
> US795027: Release preparation

- release-notes-1.1.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=846018
> US846018: Release preparation

- pom.xml
- src/main/docker/Dockerfile
- src/main/docker/log4j2.properties
- src/main/docker/scripts/start.sh
- src/test/java/com/github/cafapi/opensuse/opensearch2/ContainerIT.java
- src/test/resources/simplelogger.properties
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=868108
> US868108: Update Copyright statements to 2024

- README.md
- release-notes-1.2.0.md
- src/main/docker/Dockerfile
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=889116
> US889116: Replace gosu with su-exec

- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=898097
Same changes as in [opensuse-opensearch1-image#35](https://github.com/CAFapi/opensuse-opensearch1-image/pull/35)
> US898097: Reworked build to remove packages from image

- pom.xml
- release-notes-2.1.0.md
- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=914373
> US914373: Updated to OpenSearch 2.14.0

- pom.xml
- release-notes-2.1.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=914428
> I914428: Remove commons-text from exclusion

- release-notes-2.1.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=914373
> US914373: Release preparation

- pom.xml
- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=914373
> US914373: Revert "US888096: Use docker image version management plugin (#20)"

- pom.xml
- release-notes-2.2.0.md
- src/test/java/com/github/cafapi/opensuse/opensearch2/ContainerIT.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=914108
> US914108: Version Currency: JUnit 5 migration

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=938060
> I938060: Remove digest for dynamic opensearch image

- pom.xml
- release-notes-2.2.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=920085
> US920085: Release preparation

- README.md
- pom.xml
- release-notes-2.2.0.md
- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=929026
> US929026: Updated to run on Java 21

- pom.xml
- release-notes-2.3.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=952026
> US952026: Release preparation

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=956022
> US956022: Revert update to docker versions plugin for release

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=972011
> US972011: updated to docker image version plugins release

- pom.xml
- release-notes-2.3.8.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1011076
> US1011076: Release preparation

- pom.xml
- release-notes-2.3.9.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1019001
> US1019001: Release preparation

- pom.xml
- release-notes-2.3.10.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1027037
> US1027037: Release preparation

- pom.xml
- release-notes-2.3.11.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1031054
> US1031054: Release preparation
